import type { Metadata } from "next";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import Header from "./component/Header";
import Footer from "./component/Footer";
import { AuthProvider } from "./context/AuthContext";
import { CartProvider } from "./context/CartContext";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { cookies } from "next/headers";
import { jwtVerify } from "jose";
import type { JWTPayload } from "jose";

export const metadata: Metadata = {
  title: "dyut motors",
  description: "Generated by create next app",
};

// ✅ Async function to extract user from cookie
async function getUserFromCookie(): Promise<JWTPayload | null> {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;

  if (!token) return null;

  try {
    const secret = new TextEncoder().encode(process.env.JWT_SECRET);
    const { payload } = await jwtVerify(token, secret);
    return payload;
  } catch (err) {
    console.error("Token verification failed", err);
    return null;
  }
}

// ✅ Mark RootLayout as async to await user data
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUserFromCookie();

  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <CartProvider>
            <Header user={user} />
            {children}
            <ToastContainer position="top-right" autoClose={3000} />
            <Footer />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
